Ticket/2898 upgrade fixes like workflow
NCIOCPL/cgov-digital-platform pull request #2905
Opened 2020-09-08 18:29 UTC by bryanpizzillo

2020-09-22 17:31 UTC, blairlearn requested changes

2020-09-23 19:51 UTC, VictoriaSunNIH commented
The Tasks bar has changed. View in Edit form is no longer showing above "Show Revisions".  And "Edit content" appears now above workflow actions.  This edit content should be moved to be below workflow actions, and above show revisions, as well as renamed "view in edit form."
![image](https://user-images.githubusercontent.com/31222859/94062378-968d3a80-fdb4-11ea-9acc-cac5e3ada26c.png)

**DEV (this is correct):**
![image](https://user-images.githubusercontent.com/31222859/94062358-8ecd9600-fdb4-11ea-9a01-2cabc92d665d.png)


**TEST (this is incorrect):**

2020-09-23 19:54 UTC, bryanpizzillo commented
Here is a list of the various third party module changes for this release.
[Third Party Module Changes D8.7->D8.9.pdf](https://github.com/NCIOCPL/cgov-digital-platform/files/5271544/Third.Party.Module.Changes.D8.7-.D8.9.pdf)

2020-09-24 00:34 UTC, bryanpizzillo commented on docroot/.htaccess.orig
> +#
I removed it and added to git ignore

2020-09-24 03:12 UTC, bryanpizzillo commented
> The Tasks bar has changed. View in Edit form is no longer showing above "Show Revisions". And "Edit content" appears now above workflow actions. This edit content should be moved to be below workflow actions, and above show revisions, as well as renamed "view in edit form."
> 

@VictoriaSunNIH  can you please test this on http://ncigovcdode385.prod.acquia-sites.com/? I updated everything and I think it is right now.

2020-09-24 15:30 UTC, blairlearn commented
An "oddity" -- I'm seeing that some -- but not all -- users on the test environment no longer have their email addresses set.

e.g. user `olssonja` has no email address.  Ditto for `tanenbaumag`.  On the other hand, `welshja` and `mashkinaea` have the sort of "filler" addresses one would expect from staging to the  lower tier.

2020-09-24 17:02 UTC, VictoriaSunNIH commented
Promotional Image and Override Promotional Image - no matter what image you select, the Drupal field says 'Breast Cancer in Women'. The front-end will display the correct image, but the Promotional Image field does not display the correct image name here.

2020-09-24 18:17 UTC, VictoriaSunNIH commented
@bryanpizzillo  - another UI change that we need to address: For all the content types, under URL Redirects on the right hand side of the CMS interfact, there is a new Extra button called "Add URL Redirects" appearing.  This change needs to be addressed.  We should hide that button since only IAs are allowed to do this
![image](https://user-images.githubusercontent.com/31222859/94183615-b08c5300-fe70-11ea-84d0-61d6d91b7500.png)

2020-09-25 21:18 UTC, lburack commented
@bryanpizzillo - the video carousel controls are missing at mobile breakpoints on the front end. On mobile, it displays as though there's only one video; there's no way to see that this is a carousel, including inability to swipe. 

https://www-test-acsf.cancer.gov/news-events/press-releases/2015/mini-test
versus
https://www.cancer.gov/types/childhood-cancers (video is under last OTP section, Research)

![video-carousel-mobile](https://user-images.githubusercontent.com/29731392/94316860-2a950880-ff53-11ea-950e-7dde57493b25.jpg)

2020-09-28 15:11 UTC, merged