Ticket/dceg connect tickets 2
NCIOCPL/cgov-digital-platform pull request #3060
Opened 2021-05-17 20:29 UTC by erikscottmeyer

2021-05-17 21:53 UTC, blairlearn requested changes

2021-05-17 21:53 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/connect/entrypoints/Connect.scss
> +     // color: $section-menu-mobile-tablet-family-active-color;
Same

2021-05-17 21:53 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/connect/entrypoints/Connect.scss
> +    //    color: $section-menu-mobile-tablet-family-active-color;
Same

2021-05-17 21:53 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/connect/entrypoints/Connect.scss
> +    //background: $section-menu-mobile-tablet-family-active-background;
And again

2021-05-17 21:53 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/connect/entrypoints/Connect.scss
> +   // background: $section-menu-mobile-tablet-family-active-background;
And here

2021-05-17 21:53 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/connect/entrypoints/Connect.scss
> +    color: $section-menu-mobile-tablet-family-active-color;
Please remove code rather than commenting it out. Commented out code becomes "noise" when you're reading the file or worse, trying to do a search.

2021-05-19 13:16 UTC, arcepaul approved these changes

2021-05-19 14:16 UTC, blairlearn approved these changes

2021-05-25 13:46 UTC, merged