(#3054) Update spanish date display
NCIOCPL/cgov-digital-platform pull request #3168
Opened 2021-09-16 19:45 UTC by suryatheja-muppalla

closes #3054 

Fixed the Spanish date format for this ticket.

2021-09-22 19:33 UTC, adriancofie requested changes

2021-09-22 19:33 UTC, adriancofie commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Field/FieldFormatter/CgovSpanishDateFormatter.php
> +  public function settingsForm(array $form, FormStateInterface $form_state) {
Please update the description and options to accurately reflect what the formatter is doing.

2021-09-22 19:39 UTC, adriancofie approved these changes

2021-09-23 14:50 UTC, VictoriaSunNIH commented
Closing this PR - we have closed this ticket because it has already been fixed on Prod.

2021-09-23 14:50 UTC, closed without merging