Tickets/sbir custom homepage
NCIOCPL/cgov-digital-platform pull request #3330
Opened 2022-03-24 15:22 UTC by erikscottmeyer

Two tickets for the SBIR Custom homepage

2022-03-28 13:26 UTC, arcepaul commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_borderless-cards.scss
> +  //color: $white;
just remove

2022-03-28 13:27 UTC, arcepaul commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_borderless-cards.scss
> +        //color: $verydarkblue;
remove

2022-03-28 13:38 UTC, arcepaul commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_sbir.scss
> +
It feels like moving to a BEM naming convention would help organization and future maintenance here

2022-03-29 19:06 UTC, alinai commented
@blairlearn , ODE 458 has a content difference on https://ncigovcdode458.prod.acquia-sites.com/news-events page w.r.t dev-ac (https://www-dev-ac.cancer.gov/news-events).

ODE url: https://ncigovcdode458.prod.acquia-sites.com/news-events
dev-ac url:  https://www-dev-ac.cancer.gov/news-events

![image](https://user-images.githubusercontent.com/28455973/160687515-fa357dea-426f-464b-bab5-544078af4747.png)

2022-03-29 20:15 UTC, bryanpizzillo requested changes
I found a couple of things listed below. 

Also, I don't think we need to make a SBIR stylesheet for these 2 raw HTML blocks. You can add a `<style>` to the raw HTML. It most certainly should not be in common.css if it does stay. This would only need to be referenced in homelanding.css if it *needs* to be a css file. (Common is referenced on every page of every website we have)

2022-03-29 20:15 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/ckeditor/Ckeditor.scss
> +@import '~Core/styles/sbir';
Can you remove the reference to SBIR in commit 1f927bdd27c8de99f539c9f523bb4670859c77d1. This is not part of ticket 3311.

2022-03-29 20:15 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.scss
> +@import '~Core/styles/sbir';
Can you remove the reference to SBIR in commit 1f927bdd27c8de99f539c9f523bb4670859c77d1. This is not part of ticket 3311.

2022-03-31 12:53 UTC, arcepaul commented
We're missing alt text on the homepage images which is showing up as errors on accessibility scan.

2022-03-31 13:20 UTC, arcepaul commented
@acsnedegar is there an svg version of event-placeholder-icon?  It doesn't look as crisp as it should, right?

2022-03-31 13:35 UTC, acsnedegar commented
@arcepaul - these icons will need to be updated with final icons from SBIR so I wouldn't worry about swapping in an svg now. We can be sure to ask for an svg from them for this block though. Thanks!

2022-04-01 21:03 UTC, bryanpizzillo commented
> @arcepaul - these icons will need to be updated with final icons from SBIR so I wouldn't worry about swapping in an svg now. We can be sure to ask for an svg from them for this block though. Thanks!

@acsnedegar If the image is being committed to this code base is *must* be final.

2022-04-04 19:57 UTC, bennettcc commented
The PR has been updated to add these icons (svg format) inline. This has been retested and passed on the ODE 446

2022-04-04 20:46 UTC, arcepaul commented
@erikscottmeyer , could you please squash those commits for #3314?  this PR should only have 2 commits, one for #3324 and one for #3311

2022-04-05 16:48 UTC, erikscottmeyer commented
This has been replaced by PR 3347: https://github.com/NCIOCPL/cgov-digital-platform/pull/3347 (needed to squash commits to one per ticket)

2022-04-05 16:48 UTC, closed without merging