(#3216) Implement footer
NCIOCPL/cgov-digital-platform pull request #3435
Opened 2022-07-01 20:38 UTC by olitharp-nci

Closes #3216 

WIP

2022-07-01 20:40 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/_usa-footer.scss
> +//TODO remove me don't let this pr get pushed with this in
Calling this out. To be fixed with https://github.com/NCIOCPL/ncids/pull/500

2022-07-15 14:54 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/usa-footer.ts
> +	const target = event.target as HTMLAnchorElement;
need to update this to event.currentTarget

2022-07-18 14:16 UTC, bryanpizzillo commented
Code looks good to me.

2022-07-18 20:50 UTC, mworrest commented
@olitharp-nci are you able to make the caret icons turn sideways when the footer accordion is closed (then turn down when it is opened)? https://publicis.invisionapp.com/overview/Header---Footer-Wireframes-cl17806xjx3ho01x42xix33gc/screens

2022-07-19 13:49 UTC, olitharp-nci commented
@mworrest 
I'm not sure when this bug was introduced, but it definitely should be rotating. I'll spin up a DS ticket and try to get it pushed through. I'll ping you on Slack when it's ready for review.

2022-07-19 14:52 UTC, meglake commented
Noting a few items from testing:
* Email sign up doesn't work (opens a 'about:blank' page)
* Spanish footer has a few items that still need to be translated:
** 'Contact Us' to 'Comuníquese'?
** 'Follow us' to 'Síganos en'

Noting that 'Comentarios y sugerencias' link (Site Feedback) wraps to second line because of how long the text is. We'll use end of sprint demo to get approval from clients to leave as is or find a fix.

2022-07-20 14:27 UTC, bennettcc commented
Adding @welshja's feedback from testing: @olitharp-nci, on the email sign-up box, the "start" event fires every time someone clicks into that box, so you can just pile up analytics events. Can we update that to only be called on the first click into that box after the page is loaded? This is not stated in the requirements above, but is a change we'd want to make to avoid pilling up analytics calls.

The other thing I noticed with analytics is that it is not firing at all on the Spanish page (https://ncigovcdode480.prod.acquia-sites.com/espanol/cancer/sobrellevar/sentimientos). Not sure if this just isn't setup, but let me know.

Everything else is working as expected.

2022-07-28 20:36 UTC, bennettcc commented
Per Slack conversation with @welshja - the issues documented on 7/20 (stacking click events from the sign up box and spanish analytics not working) have been resolved. Testing passes on the ODE

cc @olitharp-nci

2022-07-28 21:56 UTC, bryanpizzillo requested changes
Why has the package-lock been modified? Please remove.

2022-07-29 14:00 UTC, bryanpizzillo approved these changes

2022-07-29 14:00 UTC, merged