(#3242) Implement ncids breadcrumbs
NCIOCPL/cgov-digital-platform pull request #3445
Opened 2022-07-14 16:58 UTC by olitharp-nci

Closes #3242 
Closes #3419

ODE https://ncigovcdode495.prod.acquia-sites.com/

2022-08-22 13:44 UTC, bryanpizzillo requested changes
One item.

2022-08-22 13:44 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-breadcrumb/__tests__/usa-breadcrumb.test.ts
> +		// Inject the HTML into the dom.
Clean please

2022-08-24 14:00 UTC, bennettcc commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-breadcrumb/__tests__/usa-breadcrumb.test.ts
> +		// Inject the HTML into the dom.
Tagging @olitharp-nci

2022-08-24 21:37 UTC, bryanpizzillo requested changes
The flag for always showing the breadcrumbs, even when home is the only item, needs to be set to show. In the new world, there is never a condition where the breadcrumb "Home" shows. It is always going to be "Home > current page". You can see this on the `/pets` -- the bread crumb should say "Home > Pets".

This will be updating `docroot/profiles/custom/cgov_site/config/install/block.block.ncids_trans_ncids_breadcrumb.yml` 

```
settings:
  id: ncids_breadcrumb
  label: 'NCIDS Breadcrumb'
  provider: cgov_core
  label_display: '0'
```

Will become
```
settings:
  id: ncids_breadcrumb
  label: 'NCIDS Breadcrumb'
  provider: cgov_core
  label_display: '1'
```

2022-08-25 21:06 UTC, bennettcc commented
@welshja and @nicolecrom confirmed that analytics AC's look good on ODE496

2022-08-30 14:20 UTC, olitharp-nci commented
> The flag for always showing the breadcrumbs, even when home is the only item, needs to be set to show. In the new world, there is never a condition where the breadcrumb "Home" shows. It is always going to be "Home > current page". You can see this on the `/pets` -- the bread crumb should say "Home > Pets".
> 
> This will be updating `docroot/profiles/custom/cgov_site/config/install/block.block.ncids_trans_ncids_breadcrumb.yml`
> 
> ```
> settings:
>   id: ncids_breadcrumb
>   label: 'NCIDS Breadcrumb'
>   provider: cgov_core
>   label_display: '0'
> ```
> 
> Will become
> 
> ```
> settings:
>   id: ncids_breadcrumb
>   label: 'NCIDS Breadcrumb'
>   provider: cgov_core
>   label_display: '1'
> ```


Updates needed (for future reference) --

```yml
# block.block.ncids_trans_ncids_breadcrumb.yml

settings:
  id: ncids_breadcrumb
  label: 'NCIDS Breadcrumb'
  provider: cgov_core
  label_display: '0'
  show_home_alone: show
```

```yml
# cgov_core.schema.yml

# Settings for the NCIDS Breadcrumb
block.settings.cgov_breadcrumb:
  type: block_settings
  label: 'NCIDS Breadcrumb block configuration'
  mapping:
    show_home_alone:
      type: string
      label: 'Root Site Section Display'
```

https://ncigovcdode495.prod.acquia-sites.com/pets

2022-08-31 14:56 UTC, bryanpizzillo approved these changes
Looks great!

2022-08-31 14:56 UTC, merged