(#3268) Build NCIDS Header Block
NCIOCPL/cgov-digital-platform pull request #3449
Opened 2022-07-19 15:53 UTC by bryanpnih

Closes #3268

2022-08-09 19:03 UTC, blilianyu commented
A couple of issues:
- Mega Menu for About NCI “Explore About NCI >” the arrow is breaking on the 2nd line (in [PR527](https://github.com/NCIOCPL/ncids/pull/527) when I put in "Explore About NCI >" it was on one line)
<img width="1009" alt="About NCI Mega Menu" src="https://user-images.githubusercontent.com/51677926/183740383-c6f27d6c-7b8b-46a0-b4ac-1daf3cba4d2c.png">

- Mobile menu isn’t loading from 1023 and less
<img width="577" alt="Mobile Menu" src="https://user-images.githubusercontent.com/51677926/183740384-421a318d-77c6-40fa-bfa8-29d53f656500.png">

- on Spanish, mega menu is cutting off “p” in “Subvenciones y capacitación
<img width="1050" alt="Spanish Mega Menu" src="https://user-images.githubusercontent.com/51677926/183740387-be545162-4808-47b3-b4e5-63de1e4bd0ac.png">
"

2022-08-10 18:44 UTC, meglake commented
@bryanpizzillo updates to @blilianyu list above per our discussion:

1. Confirmed this is an accepted issue and will be re-evaluated when post launch mega menu testing is conducted (this is recorded in our Redesign/DS Teams space under the 'Team Resources' wiki)
2. Confirmed this is a non-issue as mobile menu is not part of this PR review
3. Confirmed this will be an issue that @olitharp-nci will look into as part of her current sprint work.

2022-08-10 20:10 UTC, olitharp-nci requested changes

2022-08-10 20:10 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/jsx/cgdp-jsx.ts
> +				? document.createTextNode(child as string)
You said don't just createTextNode :)

2022-08-10 20:36 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-sidenav/_usa-sidenav.scss
> +@import '@nciocpl/ncids-css/scss/components/usa-sidenav/nci-sidenav'
Fix this

2022-08-10 20:36 UTC, olitharp-nci requested changes

2022-08-10 20:36 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-sidenav/_usa-sidenav.scss
> +@import '@nciocpl/ncids-css/scss/components/usa-sidenav/nci-sidenav'
```suggestion
@import '@nciocpl/ncids-css/scss/components/usa-sidenav/nci-sidenav';
```

2022-08-11 14:11 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/jsx/cgdp-jsx.ts
> +				? document.createTextNode(child as string)
Haha. JK. JK. It already does encode.

2022-08-11 14:20 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/components/cgdp-mega-menu.tsx
> +const getCgdpMegaMenu = (mmData: CgdpMegaMenuData, id: string): HTMLElement => {
jsdoc here

2022-08-11 14:20 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/components/cgdp-mega-menu-list.tsx
> +const CgdpMegaMenuList: React.FunctionComponent<CgdpMegaMenuListProps> = (
jsdoc here

2022-08-11 20:31 UTC, kate-mashkina commented
Verified a bunch of scenarios from #3268 - didn't find any gotchas
discussed YAML updates for the megaMenu content with @bryanpizzillo

2022-08-12 13:38 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/components/cgdp-mega-menu-list.tsx
> +const CgdpMegaMenuList: React.FunctionComponent<CgdpMegaMenuListProps> = (
I updated this.

2022-08-12 13:39 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/components/cgdp-mega-menu.tsx
> +const getCgdpMegaMenu = (mmData: CgdpMegaMenuData, id: string): HTMLElement => {
Updated

2022-08-17 14:40 UTC, kate-mashkina commented
primaryNavLinkClickHandler is missing the following:
linkType
listHeadingNumber 
listItemNumber 
listHeading

2022-08-23 17:02 UTC, kate-mashkina commented
> primaryNavLinkClickHandler is missing the following: linkType listHeadingNumber listItemNumber listHeading

this is fixed

2022-09-06 15:21 UTC, olitharp-nci requested changes

2022-09-06 15:21 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu.dom.ts
> +								First Section
```suggestion
								<span>First Section</span>
```

2022-09-06 15:21 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu.dom.ts
> +								Second Section
```suggestion
								<span>Second Section</span>
```

2022-09-06 15:21 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu.dom.ts
> +								Third Section
```suggestion
								<span>Third Section</span>
```

2022-09-06 15:21 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/__tests__/cgdp-megamenu-adapter.test.ts
> +	// Click Primary
are these todos?

2022-09-06 15:21 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/components/cgdp-mega-menu.tsx
> +						>{mmData.primary_nav_label}</a>
```suggestion
						><span>{mmData.primary_nav_label}</span></a>
```

2022-09-06 15:21 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-header.html.twig
> +              <a {{link_attribs}}>{{navitem.label}}</a>
```suggestion
              <a {{link_attribs}}><span>{{navitem.label}}</span></a>
```

2022-09-07 22:14 UTC, olitharp-nci approved these changes

2022-09-13 14:46 UTC, sarinapadilla approved these changes
@bryanpizzillo @olitharp-nci , this passes product/design review per 9/7 slack thread with @nicolecrom @kate-mashkina @laurelthrash @blilianyu and myself!

2022-09-13 19:21 UTC, arcepaul approved these changes

2022-09-13 19:22 UTC, bryanpizzillo approved these changes

2022-09-13 19:23 UTC, merged