(#3385) NCIDS for Application Modules
NCIOCPL/cgov-digital-platform pull request #3470
Opened 2022-08-01 20:34 UTC by bryanpnih

Closes #3385

2022-08-19 19:03 UTC, bennettcc commented
@bryanpnih Here's the first round of feedback on application pages. Feedback on CTS and the listing pages will be added later.

**NCI Dictionary of Cancer Terms**
1)	This is probably not connected to the app work, but I clicked on this link from the dictionary: https://ncigovcdode479.prod.acquia-sites.com/syndication/widgets and the image is missing (to the right of the code box, see live site: https://www.cancer.gov/syndication/widgets)
2)	Individual page – sound icon is too close to text: https://ncigovcdode479.prod.acquia-sites.com/publications/dictionaries/cancer-terms/def/ibandronate (see live site: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/ibandronate)

**NCI Dictionary of Genetics Terms**
All good - no issues

**NCI Drug Dictionary**
1)	Individual page – sound icon is too close to text: https://ncigovcdode479.prod.acquia-sites.com/publications/dictionaries/genetics-dictionary/def/acrochordon (see live site: https://www.cancer.gov/publications/dictionaries/genetics-dictionary/def/acrochordon)

**R4R** 
https://ncigovcdode479.prod.acquia-sites.com/research/resources
1)	Probably a nonissue: On the R4R search results page, the R4R Home link and each resource link has the exit disclaimer. Is this a product of being on the ODE so the URLs aren’t directing to a .gov?

**Sitewide search** 
https://ncigovcdode479.prod.acquia-sites.com/search/results/?swKeyword=cancer
1)	After clicking the sound icon to play the pronunciation – the blue active-state outline covers part of the word ‘cancer’
2)	There is a lot of space between the page option numbers as it expands to the left (to reproduce, go to page 4). This causes the Results count and searched term to wrap.
 3)	Show # Results arrow partially covers the number of pages at bottom of the search results page

2022-08-19 20:07 UTC, sarinapadilla commented
**Dynamic/Manual Listing Pages**
1. The pager is spaced very wide and wonky. Once you get to page 2, the addition of the `< Previous` juts up to the "Trials 26-50 of x" and causes it to wrap. Going even further through the pager continues to add to the spacing/text wrapping issues. It looks less bad on tablet and mobile since the pager is moved to its own section, but the spacing causes it to wrap much earlier than it does on Prod.
2. The breadcrumb displays "Disease Dynamic Trial Listing Page" (or "Intervention Dynamic Trial Listing Page") because that is the level you are currently on and its name in the system. This is expected behavior, but logging that we are going to have to come up with a better name for that since it's going to show on *all* disease and intervention pages.
3. There is too much spacing between 1) trial names and descriptions, and 2) trial descriptions and locations, for each listed trial.
4. Because of the spacing above, there is no clear distinction between each of the listed trials. The space between the description and location of one trial is the same as the space between the location and the next listed trial.
5. The LiveHelp popup has basically no styling. Doesn't float on top of the content, but rather is tacked on at the bottom of the page; text doesn't wrap; there's essentially no styling. Clicking the Chat Now and the x both work.

2022-08-19 20:27 UTC, sarinapadilla commented
**CTS**
Where to begin...

Basic Form:
1. The borders on the form fields are all kinds of broken. The top border isn't being displayed, and the sides don't extend above the form field name.
2. The spacing between the Cancer Type/Keyword form field name and text input are too close together. This also causes the text input to overlap onto the help link.
3. Autosuggest has a small space between the text input and the suggestions.
4. The clinical trials API banner floats at the bottom. This is expected, as it's what happens on Prod, but it looks...weird. Likely because we don't have a defined content area like on current CTS.

Advanced Form:
1. Same issue with form field borders as above.
2. In the Primary Cancer Type field, once a main type is selected, the inputs for Subtype, Stage, and Findings have double bordering and text box sizing issues.
3. In the Location form field, the toggle for the VA option on locations is being cut off.
4. In the Location form field, the spacing between the options is much too close. The selected option's radio button gets an outline that overlaps on the other radio buttons.
5. In the Location form field with Country/State/City option selected, the State input has double bordering and text box sizing issues.
6. In the Trial Type form field, the description of the field is overlapping onto the help button.
7. In the Trial Type form field, the healthy volunteers toggle is getting cut off.
8. In the Trial Type form field, the spacing between the options is too close. When an option's checkbox is actively selected, it gets an outline that almost overlaps the other checkboxes.
9. In the Drug/Treatment form field, the inputs for Drug/Drug Family and Other Treatments have double bordering and text box sizing issues.
10. In the Trial Phase form field, the spacing between the options is too close. When an option's checkbox is actively selected, it gets an outline that almost overlaps the other checkboxes.
11. In the Trial ID form field, the description of the field is overlapping onto the help button.
12. In the Trial Investigators form field, the description of the field is overlapping onto the help button.
13. In the Lead Organization form field, the description of the field is overlapping onto the help button.

2022-09-06 17:03 UTC, kate-mashkina commented
Two things that still persist 
CTS Advanced Form:
 toggle is cut off from the bottom at desktop and tablet , at 320 px it is also being cut off from the right side

<img width="548" alt="Screen Shot 2022-09-06 at 1 01 03 PM" src="https://user-images.githubusercontent.com/56886837/188696566-96a854c1-58f6-4fdd-a361-1f79ccc4f253.png">
<img width="701" alt="Screen Shot 2022-09-06 at 12 59 23 PM" src="https://user-images.githubusercontent.com/56886837/188696581-09c9b3bf-e675-4ef6-88f1-b4ca63e66c5b.png">
Glossary:
Pronunciation button is too close to the text
<img width="826" alt="Screen Shot 2022-09-06 at 12 34 56 PM" src="https://user-images.githubusercontent.com/56886837/188696784-fb462809-af3e-47ed-b952-31f243d0cdfe.png">

2022-09-07 13:51 UTC, bennettcc commented
@bryanpizzillo One more issue on sitewide search:

When clicking the pronunciation button of the searched term, the active state blue outline (around the megaphone) covers a part of that term

![image](https://user-images.githubusercontent.com/22639543/188895143-531355fb-37c9-438f-b096-9b0b559795f4.png)

2022-09-07 20:05 UTC, blilianyu commented
**General**
- on Safari, search icon is not showing in mobile menu 
![Screen Shot 2022-09-07 at 3 45 48 PM](https://user-images.githubusercontent.com/51677926/188963799-b9224351-579f-4b52-94a7-cd49250e6eb1.png)


**CTS**
- on Chrome, Firefox & Safari, clinical trial modal seems to be appearing at the bottom below pagination
![Screen Shot 2022-09-07 at 3 37 21 PM](https://user-images.githubusercontent.com/51677926/188962662-03084db8-dc05-414b-b073-796aa3ff9a32.png)
![Screen Shot 2022-09-07 at 3 38 40 PM](https://user-images.githubusercontent.com/51677926/188962665-a0a241d8-54a1-40fd-b6a1-cc0b919246fb.png)


**Dynamic Listing Pages & Manual Listing Pages**
- on Chrome, Firefox & Safari, pagination spacing is larger than CTS & R4R
![Screen Shot 2022-09-07 at 3 44 36 PM](https://user-images.githubusercontent.com/51677926/188963838-3fd2fa46-4bb9-4f18-9f81-20d8ce4048fd.png)

**Glossaries**
- Chrome & Firefox, Speaker icon is extremely large and the focus cuts it off 
![Screen Shot 2022-09-07 at 3 49 05 PM](https://user-images.githubusercontent.com/51677926/188964411-f8a608ac-c066-4921-a210-76bad9e847ce.png)
- Safari, speaker icon is cut off
![Screen Shot 2022-09-07 at 3 50 27 PM](https://user-images.githubusercontent.com/51677926/188964555-3982458a-58bf-4d63-9385-94c5ca58d2ca.png)
- Chrome, Firefox & Safari, speaker icon is running into pronunciation
![Screen Shot 2022-09-07 at 3 50 59 PM](https://user-images.githubusercontent.com/51677926/188964644-8ffed492-e33c-4318-b4ad-d8cabdcfcb1d.png)

**Sitewide Search**
- Chrome, Firefox & Safari, pagination spacing is larger than CTS & R4R
![Screen Shot 2022-09-07 at 3 57 14 PM](https://user-images.githubusercontent.com/51677926/188965680-6950e5e5-deea-48f8-a756-7c16d60ff0ba.png)

**R4R**
- Chrome, Firefox & Safari, there is an external link icon after every item when there shouldn't be and after R4R home link
![Screen Shot 2022-09-07 at 3 59 44 PM](https://user-images.githubusercontent.com/51677926/188966211-c0050dd9-1655-4086-9e0b-e1e03423b4b3.png)
![Screen Shot 2022-09-07 at 4 02 21 PM](https://user-images.githubusercontent.com/51677926/188966624-6e86b0de-66dc-4d07-9110-9685c3191559.png)

2022-09-14 16:44 UTC, bryanpizzillo commented
>This is probably not connected to the app work, but I clicked on this link from the dictionary: https://ncigovcdode479.prod.acquia-sites.com/syndication/widgets and the image is missing (to the right of the code box, see live site: https://www.cancer.gov/syndication/widgets)
So 2 things, 
1. this only works on ACSF, and maybe only live.
2. This is not an image but the actual working widget.

Gonna call this something to test in ACSF.

2022-09-19 14:11 UTC, olitharp-nci requested changes

2022-09-19 14:11 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/r4r/exitDisclaimerHandler.js
> +        /^https?:\/\/([a-zA-Z0-9-]+)+/i.test(link.href) &&
undo the changes to this file

2022-09-19 14:11 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/page--cgov-application-page--left-nav.html.twig
> +<!-- NOTIFICATIONS HERE -->
add site alerts

2022-09-19 14:11 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/page--cgov-application-page--no-left-nav.html.twig
> +<!-- NOTIFICATIONS HERE -->
add site alerts

2022-09-19 14:57 UTC, bennettcc commented
Internal testing round 3, beginning 9/19

2022-09-19 16:05 UTC, dev-rana-publicis commented
Note: The R4R pages will still have the external link icon for non-external links when viewed on an ODE or locally due to the way the regex statement is formatted. The regex statement checks if the URL is a .gov, hence it will not work on our .com ODE.

2022-09-19 18:20 UTC, laurelthrash commented
Issue related to CTS Proactive Chat Pop-up: Identified during testing on 09/19. The body text in the proactive chat pop-up maintains the former body style (screen shot). Cc: @olitharp-nci
![image](https://user-images.githubusercontent.com/102998716/191085516-dd8bb3ff-8af2-40de-9012-e21c31069945.png)

2022-10-21 17:21 UTC, closed without merging