Ticket/3256 page options
NCIOCPL/cgov-digital-platform pull request #3506
Opened 2022-08-29 16:24 UTC by dev-rana-publicis

ODE:
Closes: #3256

2022-09-06 18:04 UTC, olitharp-nci requested changes

2022-09-06 18:04 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-page-options/cgdp-page-options.ts
> +	// const pageOptions = document.querySelectorAll('.cgdp-page-options');
removed unused code

2022-09-06 18:04 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/translations/cgov_site.es.po
> +msgstr "Opciones de la página al final"
add blank line to end of file

2022-09-06 18:39 UTC, olitharp-nci requested changes

2022-09-06 18:39 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-page-options/cgdp-page-options.ts
> +	console.log(location);
whoops. still have a console.log here

2022-09-06 18:59 UTC, olitharp-nci approved these changes

2022-09-07 14:07 UTC, kate-mashkina requested changes

2022-09-07 14:07 UTC, kate-mashkina commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-page-options/cgdp-page-options.ts
> +	trackOther('PreHeader:LinkClick', 'PreHeader:LinkClick', {
This code is for language toggle, page options have different event name `PageOptions:LinkClick`- please refer to to AC

2022-09-07 15:12 UTC, olitharp-nci requested changes

2022-09-07 15:12 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/layout/page_options_macros.twig
> +  <button class="usa-button usa-button--unstyled" onclick="window.print()"><svg class="usa-icon " role="img" aria-hidden="true"><use href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My
```suggestion
  <button class="usa-button usa-button--unstyled" onclick="window.print()">
  <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24" class="usa-icon" role="img" aria-labelledby="print-title">
    <title id="print-title">{{aria_label}}</title>
    <path d="M0 0h24v24H0z" fill="none"/>
    <path d="M19 8H5c-1.66 0-3 1.34-3 3v6h4v4h12v-4h4v-6c0-1.66-1.34-3-3-3zm-3 11H8v-5h8v5zm3-7c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm-1-9H6v4h12V3z"/>
  </svg>
  </button>
```

2022-09-07 15:12 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/layout/page_options_macros.twig
> +  <a class="usa-button usa-button--unstyled" href="mailto:?subject=Information from the National Cancer Institute Web Site &body=I found this information on www.cancer.gov and I'd like to share it wi
```suggestion
  <a class="usa-button usa-button--unstyled" href="mailto:?subject=Information from the National Cancer Institute Web Site &body=I found this information on www.cancer.gov and I'd like to share it with you: {{ url }}">
    <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24" class="usa-icon" role="img" aria-labelledby="email-title">
        <title id="email-title">{{aria_label}}</title>
        <path d="M0 0h24v24H0z" fill="none"/>
        <path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 14H4V8l8 5 8-5v10zm-8-7L4 6h16l-8 5z"/>
    </svg>
  </a>
```

2022-09-07 20:05 UTC, olitharp-nci approved these changes

2022-09-12 13:46 UTC, bennettcc commented
Per slack discussion on 9/9, this PR passes product/design review.

Awaiting final tech review and approval from @bryanpizzillo @arcepaul before merging in

2022-09-12 21:29 UTC, kate-mashkina approved these changes

2022-09-12 22:16 UTC, bryanpizzillo approved these changes

2022-09-12 22:16 UTC, merged