(#3386) Update Error Pages
NCIOCPL/cgov-digital-platform pull request #3517
Opened 2022-09-07 19:47 UTC by dev-rana-publicis

ODE:
Closes #3386

2022-09-09 17:06 UTC, karlikpj approved these changes

2022-09-09 17:43 UTC, olitharp-nci approved these changes

2022-09-12 13:44 UTC, bennettcc commented
Per slack conversion on 9/9, this has passed product/UX review.

Awaiting final tech review approval from @bryanpizzillo @arcepaul before it can be merged

2022-09-12 17:05 UTC, arcepaul approved these changes

2022-09-13 13:24 UTC, bryanpizzillo requested changes

2022-09-13 13:24 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_errorPage.scss
> -  padding: 0 20px;
Hrmm. Can we do this not in this file. Changing this file will change DCEG Connect. If it is simple enough you can move it to ncids_trans/front-end/legacy/styles (just follow the convention). Then import it from ncids_global. OR, we could make a new entry point for it, and move this into legacy.

2022-09-14 19:12 UTC, bryanpizzillo approved these changes

2022-09-14 19:12 UTC, merged