(#3256) Fixed Page Options Unit Test Error
NCIOCPL/cgov-digital-platform pull request #3527
Opened 2022-09-13 18:44 UTC by dev-rana-publicis

Closes #3256 

Note: No ODE. Console unit test error only.

2022-09-13 18:49 UTC, bryanpizzillo requested changes
Can you please test the print spy to see that it is called when print is clicked?

2022-09-13 19:05 UTC, dev-rana-publicis commented
> Can you please test the print spy to see that it is called when print is clicked?

Fixed!

2022-09-14 21:14 UTC, olitharp-nci approved these changes

2022-09-16 14:54 UTC, arcepaul approved these changes
LGTM - test run and pass locally

2022-09-21 20:29 UTC, bryanpizzillo approved these changes

2022-09-21 20:29 UTC, merged