(#3279) Autosuggest Setup
NCIOCPL/cgov-digital-platform pull request #3569
Opened 2022-10-03 15:58 UTC by dev-rana-publicis

ODE:
Closes #3279

2022-11-15 17:13 UTC, bryanpizzillo requested changes
This also needs a correct search icon in `docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-header.html.twig`

2022-11-15 17:13 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/cgdp-autocomplete-adapter.ts
> +		const results = JSON.parse(JSON.stringify(response)).results;
It seems like this was just copied from the example site that does *not* use Axios. So this really should be cleaned up.

2022-11-15 17:13 UTC, bryanpizzillo commented
@dev-rana-publicis I reserve the right to have other changes, but here is a bunch.

2022-11-15 17:44 UTC, bryanpizzillo requested changes
Also @dev-rana-publicis can you please remove all the package stuff and move it into a separate commit preceding this one.

2022-11-15 18:41 UTC, dev-rana-publicis commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/auto-suggest-analytics-handlers.ts
> +export const searchSubmitHandler = (event: Event) => {
I am just following what was done in the mega-menu

2022-11-17 01:21 UTC, bryanpizzillo requested changes
So I was just checking to see if the template got touched and noticed something very wrong. Please fix the two issues.

2022-11-17 01:21 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-header.html.twig
> +          <button class="usa-button nci-header-search__search-button" type="submit" aria-label="search">
This breaks translations. You can't just copy paste here. Please fix this.

Also I thought the <svg> was the problem and I don't see that being updated.

2022-11-17 01:21 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-header.html.twig
> +            <span class="nci-header-search__label">Search</span>
This breaks translations as well.

2022-11-17 20:03 UTC, bryanpizzillo approved these changes

2022-11-17 20:07 UTC, bryanpizzillo requested changes
The search button is broken on desktop, please fix.

2022-11-17 21:41 UTC, bryanpizzillo approved these changes

2022-11-17 21:41 UTC, merged