(#3709) Accordion Padding Fix
NCIOCPL/cgov-digital-platform pull request #3716
Opened 2023-01-09 21:28 UTC by dev-rana-publicis

Closes #3709

2023-01-23 16:04 UTC, bryanpizzillo requested changes

2023-01-23 16:04 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_managed-lists.scss
> +            padding-right: mq-px2em(15px);
This does not seem to be the correct fix as it is not specifically targeting accordion content.

A good example on the ODE content is https://ncigovcdode522.prod.acquia-sites.com/about-nci/organization/ccct

2023-01-24 17:55 UTC, sarinapadilla approved these changes
Looks good from testing, so approved!

2023-01-24 18:02 UTC, arcepaul approved these changes

2023-01-30 19:40 UTC, bryanpizzillo approved these changes

2023-01-30 19:41 UTC, merged