Ticket/3519 ncids without title style home landing page dev
NCIOCPL/cgov-digital-platform pull request #3748
Opened 2023-01-26 20:22 UTC by dev-rana-publicis

2023-02-21 20:15 UTC, andyvanavery commented
During client review on Feb 21, 2023, the client indicated that the images appeared "too large" at the breakpoint where the cards vertically stack. This was submitted as a Change Request which was accepted by the internal team on Feb 21, 2023. The DS Development will execute the change in the DS. Once completed, this PR can be updated with the changes necessary to implement the different breakpoint that starts the vertical stacking.

2023-02-27 15:13 UTC, arcepaul commented
Accessibility is where I would expect it to be (no new issues as a result of this code).  Except for some missing newlines at end of files, looks good to me so far.

2023-02-27 15:35 UTC, sarinapadilla approved these changes
Reviewed by clients and Product, and looks good!

2023-03-08 15:14 UTC, arcepaul commented
Your commit message is failing commitlint because of the format of that last commit. may want to reorder and squash it into one of the other commits.

2023-03-09 14:42 UTC, bennettcc commented
ODDC Feds have re-reviewed this and approve! (specifically, they reviewed the changes to the H2 link state changes

2023-04-06 18:33 UTC, andyvanavery commented
The NCIDS 3 Feature Card Row ticket #3492 was updated with new Acceptance Criteria to indicate how the Heading will display above the NCIDS 3 Feature Card Row

2023-04-10 19:02 UTC, bryanpizzillo requested changes
I have some tweaks for the placeholders.

2023-04-10 19:02 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_image/src/CgovImageGetThemeImages.php
> +  public function getThemeImages($image_style) {
change this to getPlaceholderImage.

2023-04-10 19:02 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_image/src/CgovImageGetThemeImages.php
> +      $uri = 'module://cgov_image/img/placeholder-4x3.png';
Use the `$crop` variable to get the file name so this thing scales. I.E., no switch statement.

2023-04-10 19:02 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_image/src/CgovImageGetThemeImages.php
> +    $image_style = ImageStyle::load($image_style);
You should see what happens when you handle a bad request.

2023-04-10 20:55 UTC, dev-rana-publicis commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_image/src/CgovImageGetThemeImages.php
> + * Class CgovImageGetThemeImages.
CgovImageTools is the twig extension I am using to get findCropByStyle. Did you still want me to change CgovImageTools to CgovImageTwigExtensions?

2023-04-21 19:49 UTC, adrianacastaneda approved these changes

2023-04-25 18:22 UTC, merged