(#3488) NCIDS Hero
NCIOCPL/cgov-digital-platform pull request #3822
Opened 2023-04-14 20:44 UTC by dev-rana-publicis

Closes #3488

2023-05-16 17:57 UTC, bennettcc approved these changes

2023-05-16 17:57 UTC, bennettcc commented
Approving this on behalf of product and IA, Fed front end testers - passed on the ODE

2023-05-23 19:37 UTC, dev-rana-publicis commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-hero.html.twig
> +        <ul class="nci-cta-strip" aria-label="Call to action">
refer back to Bryan's comment

2023-05-23 19:37 UTC, dev-rana-publicis commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-hero.html.twig
> +    <div class="usa-section usa-section--dark usa-section--nci-cta-strip cgdp-cta-strip">
remove `cgdp-cta-strip`

2023-05-23 19:37 UTC, dev-rana-publicis commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-external--link-button-hero.html.twig
> +<a href="{{ paragraph.field_external_link.uri }}" alt="{{ paragraph.field_button_alt.value }}" class="nci-hero__cta-button usa-button">
refer back to Bryan's comments

2023-05-23 19:37 UTC, bryanpizzillo requested changes
Changes so far...

2023-05-23 19:37 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-internal--link-button-cta.html.twig
> +  <a href="{{ url }}" alt="{{ paragraph.field_button_alt.value }}" class="usa-button">
See the external link item comment for the `alt` attribute issue.

2023-05-23 19:37 UTC, dev-rana-publicis commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-internal--link-button-hero.html.twig
> +  <a href="{{ url }}" alt="{{ paragraph.field_button_alt.value }}" class="nci-hero__cta-button usa-button">
Bryan comment

2023-05-24 04:39 UTC, dev-rana-publicis commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-external--link-button-cta.html.twig
> +<a href="{{ paragraph.field_external_link.uri }}" alt="{{ paragraph.field_button_alt.value }}" class="usa-button">
Drupal just renders out whatever is set on the field. The link button nor the cta strip breaks if there is a single or double quote in the aria-label.

2023-05-24 20:30 UTC, dev-rana-publicis commented
Non Hero and CTA Examples:
1. NCIDS with title: http://www.devbox/ncids-landing-with-title
    - title (0px top, 32px bot)
    - r2.1 component double spacing (16px)
2. NCIDS without title: http://www.devbox/ncids-guide-card-test
    - r2.1 component (32px)
3. NCIDS with title: {{ add on to http://www.devbox/ncids-landing-with-title}}
    - title (0px top, 32px bot)
    - r2.1 component (16px)
    - r2.1 component (16px)
4. NCIDS without title: http://www.devbox/ncids-external-feature-card-test
    - r2.1 component (32px)
    - r2.1 component (16px)

HERO EXAMPLES:
1. NCIDS with title: http://www.devbox/ncids-hero-default-test
    - title (0px top, 32px bot)
    - hero (0px top, 0px bot)
    - r2.1 component double spacing (32px)
2. NCIDS without title: http://www.devbox/ncids-hero-cta-test
    - hero (0px top, 0px bot)
    - r2.1 component (32px)
3. NCIDS with title: {{ need to make }}
    - title (0px top, 32px bot)
    - hero (0px top, 0px bot)
    - r2.1 component (32px)
    - r2.1 component (16px)
4. NCIDS without title: http://www.devbox/ncids-hero-grants-training-test
    - hero (0px top, 0px bot)
    - r2.1 component (32px)
    - r2.1 component (16px)

CTA EXAMPLES:
1. NCIDS with title: http://www.devbox/ncids-hero-default-test
    - title (0px top, 32px bot)
    - CTA (16px top, 16px bot)
    - r2.1 component double spacing (16px)
2. NCIDS without title: http://www.devbox/ncids-hero-cta-test
    - CTA (32px top, 16px bot)
    - r2.1 component (16px)
3. NCIDS with title: {{ need to make }}
    - title (0px top, 32px bot)
    - CTA (16px top, 16px bot)
    - r2.1 component (16px)
    - r2.1 component (16px)
4. NCIDS without title: http://www.devbox/ncids-hero-grants-training-test
    - CTA (32px top, 16px bot)
    - r2.1 component (16px)
    - r2.1 component (16px)

2023-06-01 21:25 UTC, bryanpizzillo approved these changes

2023-06-01 22:41 UTC, merged