(#3786) Add feature card analytics
NCIOCPL/cgov-digital-platform pull request #3854
Opened 2023-05-11 21:57 UTC by olitharp-nci

Closes #3786

2023-05-17 19:45 UTC, bryanpizzillo requested changes
It is getting there, but I think there is a bit more in the TS that you can make common.

2023-05-17 19:45 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/analytics/landing-page-contents-helper.ts
> +	const rows = document.querySelectorAll('[data-eddl]');
This should be more specific, as we have other `data-eddl-*` data attributes that are not home/landing.

2023-05-17 19:45 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/cgdp-feature-card-row.ts
> +import { trackOther } from '../../core/analytics/eddl-util';
This should be a different function that wraps trackOther... e.g.

```
  const trackLandingClick = (row: number, column: number, other) => {
   if missing stuff error
 trackOther({
     common hard coded stuff,
     row,
     blah
  })
}
```

2023-05-17 19:45 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/cgdp-feature-card-row.ts
> +import { trackOther } from '../../core/analytics/eddl-util';
This is the common function...

2023-05-17 19:45 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/cgdp-feature-card-row.ts
> +const track = (
As I look below this looks more like the common helper function.

2023-05-17 19:45 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-3-feature-card-row.html.twig
> +    <section class="usa-section usa-section--light cgdp-feature-card-row" data-eddl="feature-card">
When I said `data-eddl-something` I did not mean that everything should be `data-eddl`. This is like having `<div data="foo">` -- kind of makes it hard to use it for multiple purposes.

2023-05-23 14:48 UTC, bennettcc commented
Approving on behalf of analytics team - Joe/Allison reviewed and approved on 5/23

2023-05-23 15:07 UTC, dlescarbeau approved these changes

2023-05-24 18:44 UTC, bryanpizzillo requested changes
I got some requests...

2023-05-24 19:05 UTC, olitharp-nci commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/cgdp-feature-card-row.ts
> +		Image: 'Image',
```
  | linkText | This value will change slightly based on the linkArea. If a user clicks on the title, this should pass the text of the title value (truncate after 50). If the user clicks on the description, this should pass the text of the description value (truncate after 50). If the user clicks on the image, pass “Image”. If the user clicks on the secondary link, pass the text displayed for that link. |
  | linkArea | For feature cards, this value should be set to “Image”, “Description”, “Title”, or “Secondary Link” based on where the user clicks. If the area cannot be determined, please pass "Undefined" |
 ```

2023-05-25 18:17 UTC, bryanpizzillo requested changes

2023-05-25 18:17 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/home-landing/home-landing.ts
> +import cgdpFeatureCardRow from '../../lib/components/cgdp-feature-card-row';
This is not correct, should be `ncids-home-landing.ts`

2023-05-30 22:52 UTC, bryanpizzillo approved these changes

2023-05-30 22:53 UTC, merged