(#3303) Removed v1 CTS App module.
NCIOCPL/cgov-digital-platform pull request #3883
Opened 2023-05-31 14:23 UTC by navsunka

close #3303 - Remove CTS App module v1.

2023-05-31 16:25 UTC, bryanpizzillo requested changes
This is looking pretty good. A few items:
1. Shouldn't you remove the `app_module` entity defined by `docroot/modules/custom/cgov_cts/config/install/app_module.app_module.cgov_cts_app.yml`
2. Take a look at the .module file -- there are a bunch of theme hooks and such for the rendering of the items that got deleted.
3. You should be able to remove the `nciocpl/clinical-trial-search-client.php` composer package. (and [anything else having to do with it](https://github.com/NCIOCPL/cgov-digital-platform/blob/6a45236793dfdd6de7d98af02a7f57a867b764ae/composer.json#L17).)

2023-06-14 16:16 UTC, santwuma commented
@adriancofie are you done with reviewing this PR?

cc: @navsunka

2023-06-14 17:35 UTC, adriancofie commented
> @adriancofie are you done with reviewing this PR?
> 
> cc: @navsunka

@santwuma I wasn't tagged on this / aware of the PR until you messaged. Taking a look today however it's a big one so I'd like to be thorough.

2023-06-14 17:47 UTC, adriancofie approved these changes

2023-06-22 19:17 UTC, bryanpizzillo approved these changes

2023-06-22 19:18 UTC, merged