(#3879) Add aria-labelledby to components
NCIOCPL/cgov-digital-platform pull request #3909
Opened 2023-06-07 15:14 UTC by dev-rana-publicis

Closes #3879

2023-06-09 20:48 UTC, bennettcc commented
Andy approved this PR on 6/9 - need one more product reviewer then the checkmark should be added

2023-06-09 21:06 UTC, sarinapadilla approved these changes
Looks good to product!

2023-06-09 21:14 UTC, dev-rana-publicis commented
Current Changes:

- NCIDS Hero
  - changed from `<section>` to `<div>`
  - no longer has `aria-labelledby` (was on the `section` prior to the `div` change) and no longer has `id` on the Hero's heading
- NCIDS Call to Action Strip (Standalone)
  - changed from `<section>` to `<div>`
  - does not have `aria-labelledby`

- Call to Action Strip (Hero variant & standalone)
  - Bryan noticed (while looking at ACSF on his phone) that the link button text was not the correct color
  - This PR fixes the link button text color

2023-06-12 16:09 UTC, bryanpizzillo requested changes
Can you please look into the thing below?

2023-06-12 16:09 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-2-guide-card-row.html.twig
> +  <section class="usa-section usa-section--light cgdp-guide-card-row" aria-labelledby="{{ titleID }}" data-eddl-landing-row>
This seems wrong. Nothing has this id.

2023-06-13 20:42 UTC, arcepaul approved these changes

2023-06-13 21:21 UTC, merged