(#4002) phpstan quick fixes for twig extension files except for blog
NCIOCPL/cgov-digital-platform pull request #4008
Opened 2023-08-16 15:54 UTC by navsunka

Closes #4002

2023-08-16 19:50 UTC, bryanpizzillo requested changes
@navsunka can you please add https://github.com/NCIOCPL/cgov-digital-platform/issues/3843 as a separate commit to this? I think it makes sense to go here.

2023-08-21 16:59 UTC, alinai commented
@bryanpizzillo , As a part of Manual Testing for [PR](https://github.com/NCIOCPL/cgov-digital-platform/pull/4008), for Images, the "Credit Displaying" works as expected. We noticed that for "Prevent displaying of empty captions" the gray box is appearing for new lines entered in the Caption field in both dev-ac and ODE615. Entered #4018 for the issue.
Besides the Image verification, the other items mentioned on the ticket were verified by automation regression tests.

2023-08-21 17:03 UTC, SupriyaSaxena0605 commented
@bryanpizzillo For PR 4008, we ran the Visual regression and Cypress Functional regression on ODE 615 and verified the results. All automation tests passed.

2023-08-21 21:17 UTC, bryanpizzillo approved these changes

2023-08-21 21:17 UTC, merged