(#4019) Fixes production logout destination
NCIOCPL/cgov-digital-platform pull request #4020
Opened 2023-08-22 13:46 UTC by jfrank-nih

Closes #4019

2023-08-22 13:49 UTC, bryanpizzillo requested changes

2023-08-22 13:49 UTC, bryanpizzillo commented on docroot/sites/settings/cgov_core.settings.php
>    case '01live':
Given this issue, can we move 01live below the dev blocks? Just that would have highlighted the missing break.

2023-08-22 14:15 UTC, bryanpizzillo commented on docroot/sites/settings/cgov_core.settings.php
> +  // Production for default, including 01live
Can you please move the comment right above `$config`? It breaks up the switch readability.

2023-08-22 15:12 UTC, blairlearn approved these changes

2023-08-25 19:21 UTC, alinai commented
@bryanpizzillo , @jfrank-nih ,tested and the test result was verified by @jfrank-nih. Thanks @jfrank-nih for confirming the test result!

2023-08-29 14:50 UTC, bryanpizzillo approved these changes

2023-08-29 14:51 UTC, merged

2023-09-05 20:07 UTC, SupriyaSaxena0605 commented
@bryanpizzillo @jfrank-nih Verified the log out page on CMS-dev.