(#4106) Fix role permission assigning
NCIOCPL/cgov-digital-platform pull request #4107
Opened 2023-10-15 18:30 UTC by bryanpizzillo

role_delegation removes all roles from site admin under certain conditions. This disables the module and provides an alternate method.

Closes #4106

2023-10-16 14:19 UTC, KateMashkinaNIH commented
no option to filter users on the people tab
<img width="1522" alt="Screenshot 2023-10-16 at 10 14 10 AM" src="https://github.com/NCIOCPL/cgov-digital-platform/assets/67657582/d3a8b2c9-1277-4e98-b1ec-600526eff101">

2023-10-16 15:28 UTC, blairlearn requested changes

2023-10-16 15:28 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
> +  }
This needs a comment to explain what it's doing and why.

Also, the hook's comment block is no longer correct.

2023-10-16 17:08 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php
> +    }
Removed comment

2023-10-16 17:11 UTC, bryanpizzillo commented
> no option to filter users on the people tab <img alt="Screenshot 2023-10-16 at 10 14 10 AM" width="1522" src="https://user-images.githubusercontent.com/67657582/275548369-d3a8b2c9-1277-4e98-b1ec-600526eff101.png">

Yeah this was because `role_delegation` did some altering of the people view, which made it a dependency. When the module was uninstalled it deleted the view. Since this view is part of core it is not part of our configuration and was not something that would be re-installed by Features.

This has been addressed in the latest push.

2023-10-17 14:30 UTC, KateMashkinaNIH commented
this passes QA

2023-10-17 14:44 UTC, blairlearn approved these changes

2023-10-17 14:45 UTC, merged