(#4050) Fix PHPStan issues in Redirect Manager.
NCIOCPL/cgov-digital-platform pull request #4126
Opened 2023-10-23 14:24 UTC by bryanpizzillo

- This required lots of refactoring and includes a new working test.

Closes #4050

2023-10-23 17:40 UTC, navsunka approved these changes

2023-10-24 13:50 UTC, blairlearn requested changes

2023-10-24 13:54 UTC, bryanpizzillo commented
@KateMashkinaNIH The steps for testing this will be:
1. Make a CSV file of redirects.
    * There should be no header row
    * The format is `/from_url, /to_url` 
    * Test Spanish too.  
    * /to_url can be external
1. Login to the ODE as a site admin
3. Go to /admin/config/search/cgov-redirect-manager
4. Upload your csv file
5. SSH to the ODE
6. `cd /var/www/html/<ODE>`
7. `drush queue:run cgov_redirect_manager_queue_worker`
8. Go to /admin/config/search/redirect and you should see your URLs
9. You should be able to go to any of the /from_url on the ODE and get redirected to the corresponding /to_url url

2023-10-24 14:06 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/CgovImporterService.php
> +    });
Well read IS always expected to return messages, actually technically it is not, it is expected to return a "tuple-like thing cause PHP does not have tuple, but it does have array destructuring," with messages being the second element.

However, if your updated argument is that if you are writing these methods in a functional programming style, you really should not be modifying the array coming out of read, then I can buy that.

2023-10-24 14:10 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/CgovImporterService.php
> +        $this->messenger->addStatus($this->t('Skipping the header row.'));
I am just going to remove the message as IDK why it would be there...

2023-10-24 14:19 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/CgovImporterService.php
> +    });
I dislike variables which are dependent on a return in order to point to a specific type.  A functional style would help address this.

Also, I got the `array_merge` partially wrong. The merged array is the return value, not a side-effect.  So, that line should really be

```php
$messages = array_merge($messages, $readMessages);
```

(Or, in a strict functional style, some new variable.)

2023-10-24 15:20 UTC, bryanpizzillo reviewed
I have to submit a review for my own PR to respond to the various conversations from Blair's review... silly.

2023-10-24 15:20 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/CgovImporterService.php
> +    $status_code = '301',
Actually, it should not be named that. It **IS** the status code forced for all the redirects being processed in `readExpandLine`. I added a todo in read that we should refactor the code in `read` to not check if it is empty or not. I would have changed it, but then `readExpandLine` is sometimes returning the raw line if there was an error, and that too should be cleaned up too. So it gets messy.

2023-10-24 15:38 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/CgovImporterService.php
> +      ];
Actually, this should be `[ [], [ 'The message' ] ]` to match the above argued return type for `read` :)

2023-10-24 20:53 UTC, KateMashkinaNIH commented
all clear

2023-10-24 21:08 UTC, blairlearn approved these changes

2023-10-25 13:19 UTC, merged