(#4070) NCIDS Dynamic List
NCIOCPL/cgov-digital-platform pull request #4204
Opened 2023-12-11 17:44 UTC by dev-rana-publicis

Closes #4070

2023-12-13 15:46 UTC, bryanpizzillo requested changes
The javascript/css for the dynamic lists should be `cgdp-dynamic-list` and not `usa-collection`. The cgdp-dynamic-ist draws as a collection, but it is not JS and CSS for all collections. For example we have a "list" component that would almost certainly also render as a usa-collection. That list would be a `cgdp-list` or something. Both use usa-collection.

2023-12-18 17:18 UTC, bryanpizzillo requested changes
This is a review of c7abaa33b29dfc017339a47d9a213b0416e22cb3

2023-12-18 17:49 UTC, bryanpizzillo requested changes
The pageRowCols stuff needs to be moved to the 2 col layout. Also the logic is not going to work right in figuring out what is a row in a col and what is a row in the landingContents. The approach was discussed in Slack last week, but raw html should always be something like:

`<div class="usa-section" data-eddl-landing-row>` no matter if in the landing contents or a row.

This needs updates to how you find pageRows and pageRowIndex (across the board) to be:

```
const allRows = Array.from(
	document.querySelectorAll('[data-eddl-landing-row]')
);
const nestedRows = Array.from(
	document.querySelectorAll('[data-eddl-landing-row] [data-eddl-landing-row]')
);
const pageRows = allRows.filter((r) => nestedRows.indexOf(r) === -1);

const col = target.closest('[data-eddl-landing-row-col]');
const parentRowContainer = col ? col.closest('[data-eddl-landing-row]') : target.closest('[data-eddl-landing-row]')
const pageRowIndex = parentRowContainer
	? pageRows.indexOf(parentRowContainer) + 1
	: '_ERROR_';
```
^^^ should be turned into a helper function so it can be reused in the raw html code, which seems to duplicate the landing-page-content code.

Then you can make a helper for finding the containerItem for those things that can be in landing contents or a column with:
```
function getContainerItemInfoForTarget(target) {
   const col = target.closest('[data-eddl-landing-row-col]');
   if (col) {
      const parentColRow = target.closest('[data-eddl-landing-row]');
      const colRows = col.querySelectorAll('[data-eddl-landing-row]');
      const colItemIndex = parentColRow ? colRows.indexOf(parentColRow) + 1 : '_ERROR_';
      return {
       containerItems: colRows.length,
       containerItemsIndex: colItemIndex,
      };
   } else {
     return {
       containerItems: 1,
       containerItemsIndex: 1,
     };
   }
}
```

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/cgdp-landing-raw-html.ts
> +	const pageRowCols = parentRowContainer
This and all the raw HTML bits need to go into the 2 column commit.

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/analytics/landing-page-contents-helper.ts
> +	const pageRowCols = parentRowContainer
The core analytics here have to go into the 2 column layout commit

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-promo-block/__tests__/nci-promo-block.test.ts
> +					pageRowCols: 0,
2 col commit

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-hero/__tests__/nci-hero.test.ts
> +			pageRowCols: 0,
2 col commit

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-cta-strip/__tests__/nci-cta-strip.test.ts
> +				pageRowCols: 0,
2 col commit

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-inline-video/__tests__/cgdp-inline-video.test.ts
> +				pageRowCols: 0,
2 col commit

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.test.ts
> +				pageRowCols: 0,
2 col commit

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/__tests__/cgdp-feature-card.test.ts
> +				pageRowCols: 0,
2 col commit

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/__tests__/cgdp-landing-raw-html.test.ts
>  import { cgdpLandingRawHtmlDom } from './cgdp-landing-raw-html.dom';
Add multiple rows to the cgdpLandingRawHtmlDom example if it does not have it.

2023-12-18 17:49 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/__tests__/cgdp-landing-raw-html-cols.dom.ts
> +                <div class="ncids_dynamic_list" data-eddl-landing-item="collection">
This test dom needs to get updated to have:
1 raw html in column 1, and 2 raw html in column 2, and test cases to match.

There should be matching click handlers in the unit tests.

2024-01-03 17:23 UTC, bryanpizzillo approved these changes

2024-01-03 18:19 UTC, bennettcc approved these changes

2024-01-03 18:20 UTC, merged