(#4223) Initial Cancer Types Landing Page YAML
NCIOCPL/cgov-digital-platform pull request #4266
Opened 2024-02-22 17:12 UTC by dev-rana-publicis

Closes #4223

2024-02-27 14:39 UTC, andyvanavery31 commented
Looks good to me!

2024-02-28 14:39 UTC, adrianacastaneda approved these changes
Looks good to me as well!

2024-02-28 15:17 UTC, blilianyu commented
Looks good to me as well!

2024-02-28 15:23 UTC, bennettcc approved these changes

2024-02-28 15:24 UTC, bennettcc commented
Approving on behalf of product - Andy, Adriana, Lilian approved on 2/28

2024-03-06 16:29 UTC, bryanpizzillo requested changes
I have one small thing, otherwise it looks good.

2024-03-06 16:29 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/webpack.entries.js
> +	'addl-types-landing-page': path.resolve(__dirname, 'src/entrypoints/addl-types-landing-page/addl-types-landing-page.ts'),
Put a comment in as to what this is for. The name actually confused me for a moment. Is this "Additional Types" for "Landing Page content type?". This probably should be `addl-cancer-types-landing-page` or something to make it REAL clear what it is for.

2024-03-26 20:14 UTC, closed without merging