(#4216) Add Summary Box Row to Cancer Types Page
NCIOCPL/cgov-digital-platform pull request #4274
Opened 2024-02-29 21:51 UTC by dev-rana-publicis

Closes #4216
Closes #4268

2024-03-01 19:07 UTC, dcvijanovic1k commented
Looks good! Tested on FF/Chrome/Safari

2024-03-01 20:48 UTC, blilianyu commented
Looks great on my end too!

2024-03-04 15:48 UTC, sarinapadilla submitted a review, later dismissed
Looks great!!

2024-03-04 15:48 UTC, adrianacastaneda commented
Looks good to me! thanks!

2024-03-11 13:30 UTC, bennettcc commented
This has been approved by Federal team on 3/8

2024-03-11 17:03 UTC, arcepaul commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_cancer_types_landing_page.content.yml
> +                        <h3 class="usa-summary-box__heading" id="summary-box-key-information">
We have duplicate ids here which are being flagged.

2024-03-19 21:51 UTC, bennettcc commented
Retested after 3/19 tech fixes - passed from product

2024-03-19 21:54 UTC, bennettcc submitted a review, later dismissed

2024-03-27 18:36 UTC, monika-jaeger commented
![Screenshot 2024-03-27 at 2 32 58 PM](https://github.com/NCIOCPL/cgov-digital-platform/assets/109552399/4ef1e4c3-cb86-4899-9b74-5fb04092cbe5)
When the window is wider than approx. 1685px, the accordions do not remain in the center.

2024-03-27 21:11 UTC, bryanpizzillo requested changes
@dev-rana-publicis a few things with the HTML:
1. can you kill the non-ncids/uswds classes? (e.g., `cancer-list`)
2. I don't see any H2 elements coming before the H3, so can you make those H3 elements be H2 please? (You know to not violate accessibility...)
3. You are nesting usa-prose classes under usa-prose classes.
    * Is something in accordion causing this?
    * Technically you don't even need the `<div class="usa-prose">` wrapping the lists. you can do:
       ```
       <div class="usa-accordion">
          <h2>A</h2>
          <ul class="usa-list usa-list--unstyled">
            ...
          </ul>
          <h2>B</h2>
          <ul class="usa-list usa-list--unstyled">
          ...
          </ul>
          ...
       </div>
       ```

2024-03-28 14:20 UTC, bryanpizzillo requested changes
A couple of items.

2024-03-28 14:20 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-cancer-type-az-list.ts
> +	accordionClickTracker(target, accordionFirstInteraction);
Why do you pass in accordionFirstInteraction here? It is global.

2024-03-28 14:20 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-cancer-type-az-list.ts
> +	accordionExpandCollapseTracker(evt, accordionFirstInteraction);
Why do you pass in accordionFirstInteraction here? It is global.

2024-03-28 14:20 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-cancer-type-az-list.ts
> +	if (accordionFirstInteraction) {
This can just be `accordionFirstInteraction = false;`. The check to make sure it is true is the same CPU time as setting it to false.

2024-03-28 14:20 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-cancer-type-az-list.ts
> +	const accordionAnchorTags = document.querySelectorAll(
You really should have some other identifier for the a-z list here. I am not saying there will be other accordions on the page ever, but if we did something like update the footer to use usa-accordion like THEY use for expand/collapse this a-z specific code is going to attach events to those items.

Remember, the A-Z list is displaying its contents using a `usa-accordion` it is not *the* accordion.

2024-03-29 17:25 UTC, bennettcc commented
This has been approved by the Federal team - Alex and Jorge tested on ODE

2024-04-01 14:47 UTC, bennettcc commented
Tech review has been approved - Bryan approves on 3/29

2024-04-04 14:54 UTC, adrianacastaneda commented
Added a comment on Slack regarding a scrolling issue but otherwise looks good to me!

2024-04-05 14:17 UTC, bennettcc commented
@dev-rana-publicis @olitharp-nci Updated feedback as on 4/5, 10am:

1) Not seeing the correct width on tablet-lg
2) Analytics
	- No Results Found Event
noResultsValue now returns undefined, yesterday it returned what the user typed in
-	Select Item Event
selectedValue does not always match, for example dropdown selection “male breast cancer” returns “breast cancer”
-	Clear Form Event
clearedValue does not always match, for example dropdown selection “male breast cancer” returns “breast cancer”
-	Submit Form Event
submittedValue does not always match, for example dropdown selection “male breast cancer” returns “breast cancer”
3) Inconsistent behavior using the back button
•	Chrome will clear out combo box completely and there will be no X in the search field
•	Safari will clear out the box but there will be X in the search field
•	Firefox retains both selected term and X

2024-04-09 13:41 UTC, welshja commented
@dev-rana-publicis - I'm noticing that if you select an item and then refocus on the box, then click away again, it counts as a new select item click event. Also, if you have an item selected, then expand the dropdown and click on that same item again, it sends another select item click event. Can we make a change so that if the item selected matches the already selected item that we do not fire a new click event? Ping me if you'd like to huddle and I can show you what I'm seeing.

2024-04-10 13:32 UTC, bryanpizzillo approved these changes

2024-04-10 13:33 UTC, merged