(#4233) Allow site name in meta title
NCIOCPL/cgov-digital-platform pull request #4278
Opened 2024-03-07 17:21 UTC by navsunka

Closes #4233

2024-03-12 14:55 UTC, bryanpizzillo requested changes
One big thing, a couple of small things.

IF you can't extend the schema for the `system.site` config, then we should just make a new config and route for the editing form and make it something separate from the Basic Site Settings.

2024-03-12 14:55 UTC, bryanpizzillo commented on docroot/lib/CgovPlatform/Tests/CgovSchemaExclusions.php
> +    'system.site',
This should not be here. If you tests are complaining about things missing from the schema, you need to fix the schema.

2024-03-12 14:55 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.install
> +    // Set Default Site Branding.
Please outdent this so it aligns

2024-03-12 14:55 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.module
> +  // Validate 404 error path.
This comment looks like a copy/paste error. Please remove or update.

2024-03-20 14:50 UTC, santwuma commented
Needs final code review from @bryanpizzillo

2024-03-27 16:12 UTC, bryanpizzillo commented
@andyvanavery31, @sarinapadilla, @lburack does this pass from a product standpoint?

2024-03-27 16:15 UTC, andyvanavery31 commented
@bryanpizzillo I reviewed it, and as long as you are good with it, and haven't requested any changes that I haven't seen yet, then I'm good with it

2024-03-27 16:48 UTC, bryanpizzillo approved these changes
Looks good!

2024-03-27 16:49 UTC, merged