(#4300) Implement the responsive_favicons module
NCIOCPL/cgov-digital-platform pull request #4337
Opened 2024-05-01 18:13 UTC by navsunka

Closes #4300

2024-05-06 22:26 UTC, blairlearn requested changes

2024-05-06 22:26 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/browserconfig.xml
> +<?xml version="1.0" encoding="utf-8"?>
Remove this file.

2024-05-06 22:26 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/responsive_favicons.settings.yml
> +  - '<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#c0143c" />'
Remove these two and replace them with

```html
<link rel="icon" href="/path-to-the-original.svg" type="image/svg+xml">
```

2024-05-06 22:26 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/site.webmanifest
> +    "short_name": "",
Remove these two lines.

2024-05-06 22:26 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/site.webmanifest
> +    "display": "standalone"
Remove these lines.

2024-05-06 22:26 UTC, blairlearn commented on docroot/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/site.webmanifest
> +        }
Change the filenames to `favicon-192.png` and `favicon-512.png`. And, of course, make sure the actual filenames match.

2024-06-20 19:53 UTC, bryanpizzillo approved these changes
Looks good.

2024-06-20 19:57 UTC, merged