(#4431) Recommended Content Header Fix
NCIOCPL/cgov-digital-platform pull request #4432
Opened 2024-08-28 15:21 UTC by karlikpj

Closes #4431

2024-09-03 14:53 UTC, bryanpizzillo requested changes

2024-09-03 17:14 UTC, bryanpizzillo requested changes
You also need to revert the changes to cgov in https://github.com/NCIOCPL/cgov-digital-platform/commit/f20d312189a51cb44c2b0d5a802617ae6f9a6970.

2024-09-04 17:58 UTC, KateMashkinaNIH commented
visual regression passed https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/actions/runs/10706214792

2024-09-04 20:59 UTC, bryanpizzillo approved these changes

2024-09-04 20:59 UTC, merged