(#4379) NCIDS Summary Box - MLP
NCIOCPL/cgov-digital-platform pull request #4441
Opened 2024-09-11 16:36 UTC by dev-rana-publicis

Closes #4379

2024-09-11 20:17 UTC, bryanpizzillo requested changes
Initial quick pass: Some questions, some needed changes.

2024-09-11 20:17 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_landing_contents.yml
> +      ncids_3_feature_row_opt_head: ncids_3_feature_row_opt_head
Can you please run `drush features:list:packages` and attach to this PR? This ordering is off and features would usually mark this as having issues.

2024-09-11 20:17 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_summary_box_content.yml
> +langcode: en
So this is an approach question, but why were we not able to use the NCIDS content block's field?

2024-09-11 20:17 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_summary_box.field_summary_box_heading.yml
> +langcode: en
Do we have any other sort of heading field defined for home/landing?

2024-09-11 20:17 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/index.scss
> +@forward "usa-summary-box";
This needs to changes from the DS to reduce the heading size. See https://github.com/NCIOCPL/ncids/issues/1815 - you know what to do to comment the work around and the CGDP ticket to update.

2024-09-11 20:17 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/cgdp-summary-box.ts
> +import {
I can't see the unit tests for the analytics... am I missing something?

2024-09-11 20:17 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/field--paragraph--field-summary-box-heading--ncids-summary-box.html.twig
> +    {{- item.content['#text']|replace({'<p>': '', '</p>': ''})|raw -}}
You need to test this with italics.

2024-09-11 20:52 UTC, welshja commented
For analytics, on https://ncigovcdode820.prod.acquia-sites.com/test/ncids-mini-landing-summary-box on the summary box with no title, I'm getting "_ERROR_" as the title value. Per requirements it should be set to "Not Defined". Everything else looking good to me for analytics so far.

2024-09-12 15:45 UTC, dev-rana-publicis commented
9/12 Push:

- Changes the `usa-summary-box__heading` styles to be styled as an H3
- Fixes analytics to return `Not Defined` when there is no heading present
- Changed example page scenario to include italicized heading

2024-09-12 17:11 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_landing_contents.yml
> +      ncids_3_feature_row_opt_head: ncids_3_feature_row_opt_head
Just to follow up on this, @dev-rana-publicis  showed me his instance, and features had no issues with this file.

2024-09-12 17:15 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/cgdp-summary-box.ts
> +import {
Tests got created.

2024-09-12 17:36 UTC, bryanpizzillo requested changes
Once thing to make sure nothing changes when we update NCIDS.

2024-09-12 17:36 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/index.scss
> +	@include u-font('serif', 'md');
This needs to do what we are doing in the patch:
```
@include typeset-h3;
```

2024-09-17 18:14 UTC, dev-rana-publicis commented
9/17 Push Fixes:

- We created a new format called `NCIDS Streamlined No Headings` and set that as our CKEditor format for the summary box body content. We should expect content editors to NOT see heading formats when editing the summary box content.
- The summary box width should now be set to 88ex
- Confirm summary box heading font-size, font, and line-height
- Made the summary box an `<aside>`
- Added `usa-prose` to summary box content. Please confirm that styles look correct.

2024-09-19 14:46 UTC, welshja commented
Analytics looking good to me on the latest build!

2024-09-23 13:43 UTC, andyvanavery31 commented
@dev-rana-publicis can you please update the heading in the Summary Box to be an <h2> instead of a <div>?

2024-09-23 19:37 UTC, andyvanavery31 commented
Summary Box has been approved by the client.

2024-09-23 19:37 UTC, bryanpizzillo approved these changes

2024-09-23 19:38 UTC, merged