(#4414) NCIDS 2 Column Updates - Image & Video
NCIOCPL/cgov-digital-platform pull request #4467
Opened 2024-10-09 20:33 UTC by dev-rana-publicis

Closes #4414

2024-10-10 20:39 UTC, bryanpizzillo requested changes
Images and videos should be within a `<figure>` element using `<figcaption>` for the caption. I am going to call in @olitharp-nci on this on what we should explicitly do. E.g. is it something like:
```
<figure class="nci-figure">
   <img class="nci-image">
   <figcaption class="nci-figure__caption">
      <span class="nci-figure__source">...
   </figcaption>
```

Or,
The following where we have some figure mixins.
```
<figure class="nci-image">
</figure>
```
OR,
```
<figure class="nci-figure nci-figure--image">
</figure>
```

Figures are used all over for Images, Videos, [Tables](https://www.cancer.gov/about-cancer/treatment/cam/hp/cartilage-pdq#_82_cap). Technically MDN even suggests figures for pull quotes.

2024-10-14 17:08 UTC, bryanpizzillo requested changes
Overall comments so I don't have to write them for each aspect ratio:
1. The cgov_image display modes should not be named `ncids_aspect_ratio_X_Y`. 
    * Once again the `ncids_image` paragraph name is a little vague, but whatever. 
    * This is going to suck a but it should follow what we have been doing for other components. 
       * The labels should be `Image Display: NCIDS Image: XxY Crop` 
       * The machine names should be `ncids_image_ncids_image_XxY`. 
          * Yes, I see `ncids_image` is there twice, but it is following what we did for Promo, Feature Cards and Flag Cards. 
2. You need different image styles for each of the renderings. Do not reuse `ncids_featured` or `ncids_promo`. You should have your own set of display modes and they need to set the max width to whatever the appropriate max width is for these use cases.  The image style is for the presentation use of that image, not some sort of generic thing.

2024-10-14 18:15 UTC, bryanpizzillo requested changes
A few more items

2024-10-14 18:15 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-video/index.scss
> +// keeping these terrible names for backwards compatibility
Why are you keeping these horrible names? You are making CSS and if something else is generating that CSS, but not used by MLP, BUT someone adds it someday, you get a conflict. So if you *have* to keep it, then nest it under `.cgdp-video`.

2024-10-14 18:15 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-video/index.scss
> +.video-preview--play-button {
Same as above. Also `--play-button` is a bad name, `__play-button` would be an element. I assume this follows the "keeping horrible names".

2024-10-14 18:15 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/image/image_macros.twig
> +{% macro ncidsImageHandler(image, caption, credit, crop) %}
Ok, so this file is in the wrong place or is the wrong specificity. So in theory this macro could generically draw a "cgdp-image" in whatever container or usage. However, the image_style in use really depends on the caller. Additionally, the aspect ratio depends on the cgov_image display mode being used. So this logic is blurring cgov_image and cgov_home_landing concerns. I feel like you need to have this macro, call it `cgdpImageHandler` and the image passed in should either be the placeholder or the real image.

2024-10-14 20:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/image/image_macros.twig
> +      {{ image }}
This logic should use the image to determine which image style was used.

2024-10-14 20:45 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/image/image_macros.twig
> +{% macro ncidsImageHandler(image, caption, credit, crop) %}
Make the Crop be no_image_style

2024-10-14 21:05 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-video/index.ts
> +};
This should go into cgdp-video

2024-10-17 20:01 UTC, blilianyu commented
@dev-rana-publicis @dlescarbeau 
Looks great but a couple things:
- Credit field should be optional
- Video caption margin is showing -4px top but it seems even smaller than Images. Can we make it the same?
<img width="494" alt="Screenshot 2024-10-17 at 3 59 50 PM" src="https://github.com/user-attachments/assets/0dd48dcf-3753-4499-a044-8872f9054f44">

2024-10-18 14:30 UTC, bryanpizzillo requested changes
Requesting changes for me to make - but also requirements.

2024-10-18 14:30 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.module
> +    $crop_display = $entity->field_image_aspect_ratio->value;
See the note below about the change to either the field or the values.

2024-10-18 14:59 UTC, bryanpizzillo requested changes

2024-10-18 14:59 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/image/image_macros.twig
> +        <p>Credit: {{ credit }}</p>
This needs to be translated,.

2024-10-18 14:59 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/image/image_macros.twig
> +        <p>Credit: {{ credit }}</p>
This needs to be translated. `{% trans %}Credit{% endtrans %}`

2024-10-18 17:25 UTC, KateMashkinaNIH commented
1. Caption is not displayed on 16:9 ( english and spanish) 
2. Credit field is not translated
3. https://github.com/NCIOCPL/cgov-digital-platform/issues/4472 - it was just discovered, but it affects this component along with lists, promo blocks etc ( anywhere where NCIDS 1:1 override is used )

2024-10-24 17:34 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.module
> +    $crop_display = $entity->field_image_aspect_ratio->value;
I changed the name to `field_ncids_img_para_ratio` so that we know it is specifically for the NCIDS Image paragraph.

2024-10-24 17:34 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_image_aspect_ratio.yml
> +      label: 16x9
I changed the name to `field_ncids_img_para_ratio` so that we know it is specifically for the NCIDS Image paragraph.

2024-10-24 17:37 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/image/image_macros.twig
> +        <p>Credit: {{ credit }}</p>
This is now translated.

2024-10-25 14:40 UTC, sarinapadilla commented
Per client feedback on 10/24:
* Keeping the caption/credit styling as is
* Uupdating caption font size to `2xs` (14px)
* Updating credit font size to `3xs` (13px)

2024-10-29 13:56 UTC, bennettcc commented
Federal team has approved this PR - reviewed by Anna and Alex on 10/29

2024-10-29 16:37 UTC, andyvanavery31 approved these changes
Passes product review.

2024-10-29 18:21 UTC, bryanpizzillo approved these changes

2024-10-29 18:21 UTC, merged