(#4506) Upgrade to D10.3.x
NCIOCPL/cgov-digital-platform pull request #4519
Opened 2024-12-06 17:00 UTC by bryanpizzillo

Closes #4506

2025-01-08 21:06 UTC, blairlearn requested changes

2025-01-08 23:11 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovMegaMenuController.php
> +  public function getMegaMenu(?TermInterface $taxonomy_term = NULL) {
Backlogging as https://github.com/NCIOCPL/cgov-digital-platform/issues/4538 since this change is not changing the logic from what it is today. (AS-IS). Checking for null would actually change the logic code. Agreed it is bad.

2025-01-08 23:11 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovNavTreeController.php
> +  public function getSectionNav(?TermInterface $taxonomy_term = NULL) {
Backlogging as https://github.com/NCIOCPL/cgov-digital-platform/issues/4538 since this change is not changing the logic from what it is today. (AS-IS). Checking for null would actually change the logic code. Agreed it is bad.

2025-01-08 23:11 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovNavTreeController.php
> +  public function getMobileNav(?TermInterface $taxonomy_term = NULL) {
Backlogging as https://github.com/NCIOCPL/cgov-digital-platform/issues/4538 since this change is not changing the logic from what it is today. (AS-IS). Checking for null would actually change the logic code. Agreed it is bad.

2025-01-08 23:12 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovNavTreeController.php
> +  protected function getNavData(TermInterface $taxonomy_term, $menu_type, $max_depth) {
Backlogging as https://github.com/NCIOCPL/cgov-digital-platform/issues/4538 since this change is not changing the logic from what it is today. (AS-IS). Checking for null would actually change the logic code. Agreed it is bad.

2025-01-09 14:21 UTC, blairlearn approved these changes
Approved, with the note about #4538.

TBH, I don't believe this problem is unique to the nav tree controller.

2025-01-09 15:03 UTC, bryanpizzillo commented
@KateMashkinaNIH said this passed in standups on 01/08/2025

2025-01-09 15:03 UTC, merged