(#4517) Create NCIDS templates for Application Pages
NCIOCPL/cgov-digital-platform pull request #4524
Opened 2024-12-11 21:59 UTC by dev-rana-publicis

Closes #4517

2024-12-20 20:44 UTC, KateMashkinaNIH commented
Styling of an app using NCIDS options looks different between CMS and FE
<img width="2294" alt="Screenshot 2024-12-20 at 3 41 46 PM" src="https://github.com/user-attachments/assets/37c4007d-d0c8-4035-8a09-77b050315fbb" />

2025-01-02 19:40 UTC, bryanpizzillo requested changes
Changes requested.

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.storage.node.field_app_module_page_template.yml
> +      label: NCIDS Hide Left Nav
Can we remove "default" from the values here?

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.theme
> +  if ($node->bundle() !== "cgov_home_landing" && $node->bundle() !== "cgov_mini_landing" && $node->bundle() !== "cgov_application_page") {
You 100% should have to update https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.module#L104. 

If you *really* need to have a node template, which you probably do to get rid of the `<article>` and other stuff, then you should add the theme suggestion hook to `cgov_application_page.module`.

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-application-page/ncids-application-page.scss
> +@forward '../../lib/components/usa-sidenav';
So if you are going to implement both with a left nav and one without, you need to make the approprate entry points. I.E. You need one with the side nave that pulls in the sidenav and then one that does not.

Also, I don't think our Drupal app modules have ever had page options. (They were not part of https://github.com/NCIOCPL/cgov-digital-platform/pull/1918, nor are they in the template now)

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-application-page/ncids-application-page.scss
> +}
This feels like an unnecessary copy-paste. We really should not need the utility clasesses as the app module's css should make nice BEM class names. Utility classes are for when we have rando HTML presentation stuff to support. (e.g., Raw HTML and WYSIWYG HTML)

Then the usa-section stuff seems just copied out of mini landing. Is this to be used by the app modules like this? (I would think this would go into the app module's css if it needs sections or not...)

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-application-page/ncids-application-page.ts
> +import './ncids-application-page.scss';
See comments on scss.

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/webpack.entries.js
> +	'ncids-application-page': path.resolve(
See comments on scss.

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.libraries.yml
> +ncids-application-page:
see comments on scss.

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.theme
> +  if ($node->bundle() !== "cgov_home_landing" && $node->bundle() !== "cgov_mini_landing" && $node->bundle() !== "cgov_application_page") {
(Yes, the code here probably should have been added to `cgov_home_landing.module` ...)

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/node--cgov-application-page--ncids-default-left-nav--full.html.twig
> +</article>
This stuff needs to not be here for NCIDS. (well, yes, `{{ content.field_application_module }}` should be here.)

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/node--cgov-application-page--ncids-default-no-left-nav--full.html.twig
> +</article>
This stuff needs to not be here for NCIDS. (well, yes, `{{ content.field_application_module }}` should be here.)

2025-01-02 19:40 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/node--cgov-application-page--ncids-default-no-left-nav--full.html.twig
> +</article>
This is where maybe you want the node--cgov-applicaiton-page--full to be just `{{ content.field_application_module }}` and update page--cgov-application-page--OLDSTUFF to include this markup.

2025-01-07 16:34 UTC, bryanpizzillo requested changes

2025-01-07 16:34 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/page--cgov-application-page--ncids-left-nav.html.twig
> +    </div>
This all should be updated to be closer to https://designsystem.cancer.gov/example-site/inner-pages/inner-page.html

2025-01-07 16:34 UTC, bryanpizzillo commented on docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/page--cgov-application-page--ncids-no-left-nav.html.twig
> +    </div>
This needs to be updated to be closer to NCIDS
https://designsystem.cancer.gov/example-site/inner-pages/inner-page.html

2025-01-07 16:57 UTC, bryanpizzillo commented
@dev-rana-publicis can you please create 2 sample pages using the `dummy_app_module` app module. This should just spit out some text that says "Application Module Placeholder" and will allow us to regression test these templates.

2025-01-28 21:59 UTC, bryanpizzillo approved these changes

2025-01-28 21:59 UTC, merged